### ISSUE TITLE
When import spotifysearch I get this error

### ISSUE THREAD

**Issue by TheLostProgrammer** [matcsantos/SpotifySearch#1]
When W run `from spotifysearch.client import Client` W recieve this error, W get this error on macOS Big Sur however the same code runs fine on an arch linux machine.

```bash
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from spotifysearch.client import Client
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/client.py", line 4, in <module>
    from .classes import Authenticator, Results
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/classes.py", line 64, in <module>
    class Album(Base):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/classes.py", line 67, in Album
    images:list[AlbumCover], artists:list[Artist], available_markets:list, release_date:str, total_tracks:int):
TypeError: 'type' object is not subscriptable```

**Comment by matcsantos** [comment]
Hey! Thank your for exposing this issue. It seems to be related to **variable names and keywords** conflicting with each other. I'm working on a fix for it right now. 😉

**Comment by matcsantos** [comment]
✅ This issue was fixed on version [0.0.3](https://pypi.org/project/spotifysearch/0.0.3/), which now is the latest version.

You can update with:
`pip install --upgrade spotifysearch`

**Comment by TheLostProgrammer** [comment]
Thanks!

**Comment by TheLostProgrammer** [comment]
Thanks for the quick fixes but I have installed the update and I have the same error still.

```bash
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from spotifysearch.client import Client
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/client.py", line 4, in <module>
    from .classes import Authenticator, Results
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/classes.py", line 65, in <module>
    class Album(Base):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spotifysearch/classes.py", line 68, in Album
    images:list[AlbumCover], artists:list[Artist], available_markets:list, release_date:str, total_tracks:int):
TypeError: 'type' object is not subscriptable
```

**Comment by matcsantos** [comment]
Looks like the version uploaded to Pypi doesn't match the current version of the wrapper. I'm uploading the right version right now and the fix will be available on PIP in a couple of minutes. 😉

**Comment by matcsantos** [comment]
✅ This issue was fixed on version [0.0.5](https://pypi.org/project/spotifysearch/0.0.5/), which is now the latest version.
The previous version didn't have the fix, so I had to upload a new version.

You can update using:
`pip install --upgrade spotifysearch`

**Comment by TheLostProgrammer** [comment]
Yeah it works! Thank you so much for your quick replies and fixes!

**Comment by matcsantos** [comment]
Great! If you have any difficult on how to work with classes or methods, you can dm me on discord: **Fenin#6660**, since the documentation is not ready yet. I'll be happy to help as soon as possible. 😉
